SportTrack/Pages/Administrator/Sports/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace SportTrack.Pages.Administrator.Sports
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public CreateModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Sport Sport { get; set; } = default!;

        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Provjera postoji li već sport s istim imenom
            var existing = await _context.Sports
                .FirstOrDefaultAsync(s => s.Name == Sport.Name);

            if (existing != null)
            {
                // Postavi TempData za prikaz poruke na view-u
                TempData["ErrorMessage"] = $"Sport već postoji! ID: {existing.Id}, Naziv: {existing.Name}";
                return Page();
            }

            _context.Sports.Add(Sport);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SportTrack/Pages/Administrator/Sports/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Authorization;


namespace SportTrack.Pages.Administrator.Sports
{
    [Authorize(Roles = "Admin")]

    public class DeleteModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public DeleteModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Sport Sport { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports.FirstOrDefaultAsync(m => m.Id == id);

            if (sport is not null)
            {
                Sport = sport;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports.FindAsync(id);
            if (sport != null)
            {
                Sport = sport;
                _context.Sports.Remove(Sport);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

SportTrack/Pages/Administrator/Sports/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Authorization;


namespace SportTrack.Pages.Administrator.Sports
{
    [Authorize(Roles = "Admin")]

    public class DetailsModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public DetailsModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public Sport Sport { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport = await _context.Sports.FirstOrDefaultAsync(m => m.Id == id);

            if (sport is not null)
            {
                Sport = sport;

                return Page();
            }

            return NotFound();
        }
    }
}

SportTrack/Pages/Administrator/Sports/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Authorization;


namespace SportTrack.Pages.Administrator.Sports
{
    [Authorize(Roles = "Admin")]

    public class EditModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public EditModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Sport Sport { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sport =  await _context.Sports.FirstOrDefaultAsync(m => m.Id == id);
            if (sport == null)
            {
                return NotFound();
            }
            Sport = sport;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Sport).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SportExists(Sport.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool SportExists(int id)
        {
            return _context.Sports.Any(e => e.Id == id);
        }
    }
}

SportTrack/Pages/Administrator/Sports/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Authorization;


namespace SportTrack.Pages.Administrator.Sports
{
    

    public class IndexModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public IndexModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Sport> Sport { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Sport = await _context.Sports.ToListAsync();
        }
    }
}

SportTrack/Pages/Administrator/Teams/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace SportTrack.Pages.Administrator.Teams
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public CreateModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name");
            return Page();
        }

        [BindProperty]
        public Team Team { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name", Team.SportId);
                return Page();
            }

            // Provjera postoji li već team s istim imenom i sportom
            var existing = await _context.Teams
                .Include(t => t.Sport)
                .FirstOrDefaultAsync(t => t.Name == Team.Name && t.SportId == Team.SportId);

            if (existing != null)
            {
                TempData["ErrorMessage"] = $"Tim već postoji! ID: {existing.Id}, Naziv: {existing.Name}, Sport: {existing.Sport.Name}";
                ViewData["SportId"] = new SelectList(_context.Sports, "Id", "Name", Team.SportId);
                return Page();
            }

            _context.Teams.Add(Team);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SportTrack/Pages/Administrator/Teams/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Authorization;

namespace SportTrack.Pages.Administrator.Teams
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public DeleteModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Team Team { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FirstOrDefaultAsync(m => m.Id == id);

            if (team is not null)
            {
                Team = team;

                return Page();
            }

            return NotFound();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.FindAsync(id);
            if (team != null)
            {
                Team = team;
                _context.Teams.Remove(Team);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

SportTrack/Pages/Administrator/Teams/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;


namespace SportTrack.Pages.Administrator.Teams
{
    
    

    public class IndexModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;

        public IndexModel(SportTrack.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Team> Team { get;set; } = default!;

        public async Task OnGetAsync()
        {
            Team = await _context.Teams
                .Include(t => t.Sport).ToListAsync();
        }
    }
}

SportTrack/Pages/Favorites.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

public class FavoritesModel : PageModel
{
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;

    public FavoritesModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public IList<UserFavorite> Favorites { get; set; } = new List<UserFavorite>();

    public async Task<IActionResult> OnGetAsync()
    {
        if (!User.Identity.IsAuthenticated)
            return Challenge();

        var userId = _userManager.GetUserId(User);

        Favorites = await _context.UserFavorites
    .Where(f => f.ApplicationUserId == userId)
    .Include(f => f.Team)
        .ThenInclude(t => t.Sport)
    .Include(f => f.Sport) 
    .ToListAsync();


        return Page();
    }

    public async Task<IActionResult> OnPostRemoveFavoriteAsync(int favoriteId)
    {
        var fav = await _context.UserFavorites.FindAsync(favoriteId);
        if (fav != null)
        {
            _context.UserFavorites.Remove(fav);
            await _context.SaveChangesAsync();
        }
        return RedirectToPage();
    }
}

SportTrack/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Models;
using Microsoft.AspNetCore.Identity;

namespace SportTrack.Pages
{
    public class IndexModel : PageModel
    {
        private readonly SportTrack.Data.ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(SportTrack.Data.ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<SportEvent> SportEvent { get; set; } = default!;
        public List<UserFavorite> UserFavorites { get; set; } = new();

        public async Task OnGetAsync()
        {
            SportEvent = await _context.Events
                .Include(e => e.AwayTeam)
                .Include(e => e.HomeTeam)
                .Include(e => e.Sport)
                .OrderByDescending(e => e.Date)
                .ToListAsync();

            if (User.Identity.IsAuthenticated)
            {
                var userId = _userManager.GetUserId(User);
                UserFavorites = await _context.UserFavorites
                    .Where(f => f.ApplicationUserId == userId)
                    .ToListAsync();
            }
        }

        public async Task<IActionResult> OnPostToggleFavoriteAsync(string type, int id)
        {
            if (!User.Identity.IsAuthenticated)
                return Challenge();

            var userId = _userManager.GetUserId(User);
            var favorite = await _context.UserFavorites
                .FirstOrDefaultAsync(f => f.ApplicationUserId == userId && (
                    (type == "team" && f.TeamId == id) ||
                    (type == "sport" && f.SportId == id)
                ));

            if (favorite == null)
            {
                var newFav = new UserFavorite { ApplicationUserId = userId };
                if (type == "team") newFav.TeamId = id;
                if (type == "sport") newFav.SportId = id;
                _context.UserFavorites.Add(newFav);
            }
            else
            {
                _context.UserFavorites.Remove(favorite);
            }

            await _context.SaveChangesAsync();
            return RedirectToPage();
        }
    }
}

SportTrack/Pages/Sports.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SportTrack.Data;
using SportTrack.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

public class SportsModel : PageModel
{
    private readonly ApplicationDbContext _context;
    private readonly UserManager<ApplicationUser> _userManager;

    public IList<Sport> Sports { get; set; } = [];
    public IList<Team> Teams { get; set; } = [];

    [BindProperty(SupportsGet = true)]
    public int? SelectedSportId { get; set; }

    [BindProperty(SupportsGet = true)]
    public string? SportQuery { get; set; }

    public SportsModel(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task OnGetAsync()
    {
        var query = _context.Sports.AsQueryable();

        if (!string.IsNullOrWhiteSpace(SportQuery))
        {
            query = query.Where(s => EF.Functions.Like(s.Name, $"%{SportQuery}%"));
        }

        Sports = await query.ToListAsync();

        if (SelectedSportId.HasValue)
        {
            Teams = await _context.Teams
                .Where(t => t.SportId == SelectedSportId)
                .ToListAsync();
        }
    }

    public async Task<IActionResult> OnPostAddFavoriteAsync(int teamId)
    {
        if (!User.Identity.IsAuthenticated)
            return Challenge();

        var userId = _userManager.GetUserId(User);

        var already = await _context.UserFavorites
            .AnyAsync(f => f.ApplicationUserId == userId && f.TeamId == teamId);

        if (!already)
        {
            _context.UserFavorites.Add(new UserFavorite
            {
                ApplicationUserId = userId,
                TeamId = teamId
            });
            await _context.SaveChangesAsync();
        }

        var team = await _context.Teams.FindAsync(teamId);
        return RedirectToPage(new { SelectedSportId = team?.SportId, SportQuery });
    }
}

SportTrack/Pages/Favorites.cshtml
@page
@model FavoritesModel

<h2>Your Favorites</h2>
@if (Model.Favorites.Count == 0)
{
    <p>You have no favorite teams or sports.</p>
}
else
{
    <ul>
        @foreach (var fav in Model.Favorites)
        {
            <li>
                @if (fav.Team != null)
                {
                    @($"{fav.Team.Name} ({fav.Team.Sport?.Name})")
                }
                else if (fav.Sport != null)
                {
                    @fav.Sport.Name
                }

                <form method="post" asp-page-handler="RemoveFavorite" asp-route-favoriteId="@fav.Id" style="display:inline;">
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                </form>
            </li>
        }
    </ul>
}
<a asp-page="/Sports">Back to Sports</a>

SportTrack/Pages/Index.cshtml
@page
@model IndexModel
@using SportTrack.Models
@inject SignInManager<ApplicationUser> SignInManager

@{
    ViewData["Title"] = "Home page";
}

@functions {
    bool IsTeamFavorite(int teamId) => Model.UserFavorites.Any(f => f.TeamId == teamId);
    bool IsSportFavorite(int sportId) => Model.UserFavorites.Any(f => f.SportId == sportId);
}

<div class="container">
    @foreach (var item in Model.SportEvent)
    {
        <div class="event-card animate-slide">
            <div class="event-header">
                <span>@item.Date.ToString("dd.MM.yyyy HH:mm")</span>
                <span class="sport-badge">
                    @item.Sport.Name
                    <form method="post" asp-page-handler="ToggleFavorite" asp-route-type="sport" asp-route-id="@item.Sport.Id" style="display:inline;">
                        <button type="submit" class="star-btn @(IsSportFavorite(item.Sport.Id) ? "star-filled" : "")" title="Toggle favorite">★</button>
                    </form>
                </span>
            </div>

            <div class="event-body flex-align">
                <div class="team-block left-block">
                    <form method="post" asp-page-handler="ToggleFavorite" asp-route-type="team" asp-route-id="@item.HomeTeam.Id" style="display:inline;">
                        <button type="submit" class="star-btn @(IsTeamFavorite(item.HomeTeam.Id) ? "star-filled" : "")" title="Toggle favorite">★</button>
                    </form>
                    <span class="team-name">@item.HomeTeam.Name</span>
                </div>

                <div class="score-box">
                    @item.HomeScore : @item.AwayScore
                </div>

                <div class="team-block right-block">
                    <span class="team-name">@item.AwayTeam.Name</span>
                    <form method="post" asp-page-handler="ToggleFavorite" asp-route-type="team" asp-route-id="@item.AwayTeam.Id" style="display:inline;">
                        <button type="submit" class="star-btn @(IsTeamFavorite(item.AwayTeam.Id) ? "star-filled" : "")" title="Toggle favorite">★</button>
                    </form>
                </div>
            </div>
        </div>
    }
</div>

SportTrack/Pages/Sports.cshtml
@page
@model SportsModel

<h2>Sports</h2>

<form method="get" asp-page="Sports" class="mb-3">
    <input type="text" name="SportQuery" value="@Model.SportQuery" placeholder="Search sports..." class="form-control" />
    <button type="submit" class="btn btn-secondary mt-2">Search</button>

    @if (Model.SelectedSportId.HasValue)
    {
        <input type="hidden" name="SelectedSportId" value="@Model.SelectedSportId" />
    }
</form>

<ul>
    @foreach (var sport in Model.Sports)
    {
        <li>
            <a asp-page="Sports" asp-route-SelectedSportId="@sport.Id" asp-route-SportQuery="@Model.SportQuery">
                @sport.Name
            </a>
        </li>
    }
</ul>

@if (Model.SelectedSportId.HasValue)
{
    var selectedSport = Model.Sports.FirstOrDefault(s => s.Id == Model.SelectedSportId);
    <h3>Teams for @selectedSport?.Name</h3>

    @if (Model.Teams != null && Model.Teams.Any())
    {
        <ul>
            @foreach (var team in Model.Teams)
            {
                <li>
                    @team.Name
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form method="post" asp-page-handler="AddFavorite" asp-route-teamId="@team.Id" style="display:inline;">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-sm btn-primary">Add to favorites</button>
                        </form>
                    }
                </li>
            }
        </ul>
    }
    else
    {
        <p><em>No teams for this sport.</em></p>
    }
}
else
{
    <p><em>Select a sport to view its teams.</em></p>
}

SportTrack/Pages/Teams.cshtml
@if (Model.Sport != null)
{
    <h2>Teams for @Model.Sport.Name</h2>

    <form method="get" asp-page="Teams">
        <input type="hidden" name="sportId" value="@Model.Sport.Id" />
        <input type="text" name="q" value="@Context.Request.Query["q"]" placeholder="Search team..." />
        <button type="submit" class="btn btn-sm btn-secondary">Filter</button>
    </form>

    @if (Model.Teams.Count > 0)

    {
        <ul>
            @foreach (var team in Model.Teams)
            {
                <li>
                    @team.Name
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form method="post" asp-page-handler="AddFavorite" asp-route-teamId="@team.Id" style="display:inline;">
                            <button type="submit" class="btn btn-sm btn-primary">Add to favorites</button>
                        </form>
                    }
                </li>
            }
        </ul>
    }
    else
    {
        <p>No teams for this sport.</p>
    }
    <a asp-page="/Sports">Back to Sports</a>
}
else
{
    <p>Sport not found.</p>
}